export const SMASH_ULTIMATE_CHARACTERS = [
  { id: 1, name: "Mario", displayName: "Mario" },
  { id: 2, name: "Donkey Kong", displayName: "Donkey Kong" },
  { id: 3, name: "Link", displayName: "Link" },
  { id: 4, name: "Samus", displayName: "Samus" },
  { id: 5, name: "Dark Samus", displayName: "Dark Samus" },
  { id: 6, name: "Yoshi", displayName: "Yoshi" },
  { id: 7, name: "Kirby", displayName: "Kirby" },
  { id: 8, name: "Fox", displayName: "Fox" },
  { id: 9, name: "Pikachu", displayName: "Pikachu" },
  { id: 10, name: "Luigi", displayName: "Luigi" },
  { id: 11, name: "Ness", displayName: "Ness" },
  { id: 12, name: "Captain Falcon", displayName: "Captain Falcon" },
  { id: 13, name: "Jigglypuff", displayName: "Jigglypuff" },
  { id: 14, name: "Peach", displayName: "Peach" },
  { id: 15, name: "Daisy", displayName: "Daisy" },
  { id: 16, name: "Bowser", displayName: "Bowser" },
  { id: 17, name: "Ice Climbers", displayName: "Ice Climbers" },
  { id: 18, name: "Sheik", displayName: "Sheik" },
  { id: 19, name: "Zelda", displayName: "Zelda" },
  { id: 20, name: "Dr. Mario", displayName: "Dr. Mario" },
  { id: 21, name: "Pichu", displayName: "Pichu" },
  { id: 22, name: "Falco", displayName: "Falco" },
  { id: 23, name: "Marth", displayName: "Marth" },
  { id: 24, name: "Lucina", displayName: "Lucina" },
  { id: 25, name: "Young Link", displayName: "Young Link" },
  { id: 26, name: "Ganondorf", displayName: "Ganondorf" },
  { id: 27, name: "Mewtwo", displayName: "Mewtwo" },
  { id: 28, name: "Roy", displayName: "Roy" },
  { id: 29, name: "Chrom", displayName: "Chrom" },
  { id: 30, name: "Mr. Game & Watch", displayName: "Mr. Game & Watch" },
  { id: 31, name: "Meta Knight", displayName: "Meta Knight" },
  { id: 32, name: "Pit", displayName: "Pit" },
  { id: 33, name: "Dark Pit", displayName: "Dark Pit" },
  { id: 34, name: "Zero Suit Samus", displayName: "Zero Suit Samus" },
  { id: 35, name: "Wario", displayName: "Wario" },
  { id: 36, name: "Snake", displayName: "Snake" },
  { id: 37, name: "Ike", displayName: "Ike" },
  { id: 38, name: "Pokémon Trainer", displayName: "Pokémon Trainer" },
  { id: 39, name: "Diddy Kong", displayName: "Diddy Kong" },
  { id: 40, name: "Lucas", displayName: "Lucas" },
  { id: 41, name: "Sonic", displayName: "Sonic" },
  { id: 42, name: "King Dedede", displayName: "King Dedede" },
  { id: 43, name: "Olimar", displayName: "Olimar" },
  { id: 44, name: "Lucario", displayName: "Lucario" },
  { id: 45, name: "R.O.B.", displayName: "R.O.B." },
  { id: 46, name: "Toon Link", displayName: "Toon Link" },
  { id: 47, name: "Wolf", displayName: "Wolf" },
  { id: 48, name: "Villager", displayName: "Villager" },
  { id: 49, name: "Mega Man", displayName: "Mega Man" },
  { id: 50, name: "Wii Fit Trainer", displayName: "Wii Fit Trainer" },
  { id: 51, name: "Rosalina & Luma", displayName: "Rosalina & Luma" },
  { id: 52, name: "Little Mac", displayName: "Little Mac" },
  { id: 53, name: "Greninja", displayName: "Greninja" },
  { id: 54, name: "Palutena", displayName: "Palutena" },
  { id: 55, name: "Pac-Man", displayName: "Pac-Man" },
  { id: 56, name: "Robin", displayName: "Robin" },
  { id: 57, name: "Shulk", displayName: "Shulk" },
  { id: 58, name: "Bowser Jr.", displayName: "Bowser Jr." },
  { id: 59, name: "Duck Hunt", displayName: "Duck Hunt" },
  { id: 60, name: "Ryu", displayName: "Ryu" },
  { id: 61, name: "Ken", displayName: "Ken" },
  { id: 62, name: "Cloud", displayName: "Cloud" },
  { id: 63, name: "Corrin", displayName: "Corrin" },
  { id: 64, name: "Bayonetta", displayName: "Bayonetta" },
  { id: 65, name: "Inkling", displayName: "Inkling" },
  { id: 66, name: "Ridley", displayName: "Ridley" },
  { id: 67, name: "Simon", displayName: "Simon" },
  { id: 68, name: "Richter", displayName: "Richter" },
  { id: 69, name: "King K. Rool", displayName: "King K. Rool" },
  { id: 70, name: "Isabelle", displayName: "Isabelle" },
  { id: 71, name: "Incineroar", displayName: "Incineroar" },
  { id: 72, name: "Piranha Plant", displayName: "Piranha Plant" },
  { id: 73, name: "Joker", displayName: "Joker" },
  { id: 74, name: "Hero", displayName: "Hero" },
  { id: 75, name: "Banjo & Kazooie", displayName: "Banjo & Kazooie" },
  { id: 76, name: "Terry", displayName: "Terry" },
  { id: 77, name: "Byleth", displayName: "Byleth" },
  { id: 78, name: "Min Min", displayName: "Min Min" },
  { id: 79, name: "Steve", displayName: "Steve" },
  { id: 80, name: "Sephiroth", displayName: "Sephiroth" },
  { id: 81, name: "Pyra", displayName: "Pyra" },
  { id: 82, name: "Mythra", displayName: "Mythra" },
  { id: 83, name: "Kazuya", displayName: "Kazuya" },
  { id: 84, name: "Sora", displayName: "Sora" },
];

export function getCharacterById(id) {
  return SMASH_ULTIMATE_CHARACTERS.find(char => char.id === id);
}

export function getCharacterByName(name) {
  return SMASH_ULTIMATE_CHARACTERS.find(char => 
    char.name.toLowerCase() === name.toLowerCase()
  );
}